[package]
name = "lists"
version = "0.1.0"
authors = ["Matt Jones <jonesmr@gmail.com>"]

[dependencies]
handlebars-iron = "*"
iron = "*"
mysql = "*"
persistent = "*"
plugin = "*"
router = "*"
rustc-serialize = "*"
url = "*"
